-- MySQL Script generated by MySQL Workbench
-- Tue Oct  2 18:04:13 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Curso`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Curso` (
  `idCurso` INT NOT NULL,
  `Division` TINYINT NOT NULL,
  `Anio` TINYINT NOT NULL,
  PRIMARY KEY (`idCurso`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`ObraSocial`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`ObraSocial` (
  `idObraSocial` INT NOT NULL,
  `Sigla` VARCHAR(45) NOT NULL,
  `domicilio` VARCHAR(45) NOT NULL,
  `Tipo` VARCHAR(45) NOT NULL,
  `Telefono` INT NOT NULL,
  PRIMARY KEY (`idObraSocial`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Medico`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Medico` (
  `Matricula` INT NOT NULL,
  `Apellido` VARCHAR(45) NOT NULL,
  `Nombre` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`Matricula`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`AptoMedico`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`AptoMedico` (
  `idAptoMedico` INT NOT NULL,
  `Estado` VARCHAR(45) NOT NULL,
  `Descripcion` VARCHAR(45) NOT NULL,
  `Fecha` DATE NOT NULL,
  `Matricula` INT NOT NULL,
  PRIMARY KEY (`idAptoMedico`),
  INDEX `fk_AptoMedico_Medico1_idx` (`Matricula` ASC),
  CONSTRAINT `fk_AptoMedico_Medico1`
    FOREIGN KEY (`Matricula`)
    REFERENCES `mydb`.`Medico` (`Matricula`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Alumno`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Alumno` (
  `Cuit` INT NOT NULL,
  `Nombre` VARCHAR(45) NOT NULL,
  `Apellido` VARCHAR(45) NOT NULL,
  `idObraSocial` INT NOT NULL,
  `idCurso` INT NOT NULL,
  PRIMARY KEY (`Cuit`),
  INDEX `fk_Alumno_ObraSocial1_idx` (`idObraSocial` ASC),
  INDEX `fk_Alumno_Curso1_idx` (`idCurso` ASC),
  CONSTRAINT `fk_Alumno_ObraSocial1`
    FOREIGN KEY (`idObraSocial`)
    REFERENCES `mydb`.`ObraSocial` (`idObraSocial`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Alumno_Curso1`
    FOREIGN KEY (`idCurso`)
    REFERENCES `mydb`.`Curso` (`idCurso`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Login`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Login` (
  `idLogin` INT NOT NULL,
  `Estado` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idLogin`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`AlumnoAptoMedico`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`AlumnoAptoMedico` (
  `Cuit` INT NOT NULL,
  `idAptoMedico` INT NOT NULL,
  `idLogin` INT NOT NULL,
  PRIMARY KEY (`Cuit`, `idAptoMedico`),
  INDEX `fk_Alumno_has_AptoMedico_AptoMedico1_idx` (`idAptoMedico` ASC),
  INDEX `fk_Alumno_has_AptoMedico_Alumno_idx` (`Cuit` ASC),
  INDEX `fk_AlumnoAptoMedico_Login1_idx` (`idLogin` ASC),
  CONSTRAINT `fk_Alumno_has_AptoMedico_Alumno`
    FOREIGN KEY (`Cuit`)
    REFERENCES `mydb`.`Alumno` (`Cuit`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Alumno_has_AptoMedico_AptoMedico1`
    FOREIGN KEY (`idAptoMedico`)
    REFERENCES `mydb`.`AptoMedico` (`idAptoMedico`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_AlumnoAptoMedico_Login1`
    FOREIGN KEY (`idLogin`)
    REFERENCES `mydb`.`Login` (`idLogin`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Usuario` (
  `idUsuario` INT NOT NULL,
  `Username` VARCHAR(45) NOT NULL,
  `Password` VARCHAR(45) NOT NULL,
  `idLogin` INT NOT NULL,
  PRIMARY KEY (`idUsuario`),
  INDEX `fk_Usuario_Login1_idx` (`idLogin` ASC),
  CONSTRAINT `fk_Usuario_Login1`
    FOREIGN KEY (`idLogin`)
    REFERENCES `mydb`.`Login` (`idLogin`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
